### PR TITLE
Parse WorksheetInfo

### PR DESCRIPTION
**Pull request by felipenoris**
This should work, but it doesn't.

Instead of a `@test` , I put a `println` because it does not output the expected value. I'm getting `0` as sheet count, and I can't tell if the error in in my pointer address arithmetic, or in the C library itself.

`println("sheetcount = ", LibXLS.sheetcount(xls))`

The property `xlsworkbook.charset` also reads an empty string.
Since both `st_sheet` and `charset` read empty values, I guess the problem is in the C API itself. Or maybe the [README file](https://github.com/libxls/libxls) is outdated.

### CODE REVIEW

**Comment by felipenoris** [comment]
Travis error on macOS looks unrelated.
But tests fail on 32bit windows, on `unsafe_string`, which looks related to pointer arithmetic.

**Comment by davidanthoff** [comment]
Maybe doing this all the way with `unsafe_load` is easier? This for example works for me:
```julia
wb = LibXLS.openxls("data/book1.xls")

_wb = unsafe_load(wb.handle)

sheet_names = [unsafe_string(unsafe_load(_wb.sheets.sheet, i).name) for i in 1:_wb.sheets.count]
```
And I would think that should allow us to handle pretty much everything?

The `struct`s I defined are not complete, but I think as long as they are complete (and correct) _up to_ the field we are interested in, things should just work :) And it is also not too difficult to translate these C structs into the equivalent julia structs, so we could just complete that work, and then we should be able to relatively easily access everything?

**Comment by felipenoris** [comment]
Nice, I'll just use that then. Looks like it was an alignment issue.

**Comment by felipenoris** [comment]
Alright, this one is ready.

**Pull request merged**
