### PR TITLE
fix Worksheet finalizer

### PR DESCRIPTION
**Pull request by felipenoris**

### CODE REVIEW

**Comment by davidanthoff** [comment]
@felipenoris Should I give you push access to the repo? I think especially in this early phase of the package it might be much easier for you to push things forward that way? Once the package is stable and registered we could go back to a PR workflow?

**Comment by felipenoris** [comment]
@davidanthoff sure!

**Comment by davidanthoff** [comment]
Done! I think maybe you could still open PRs, but you can just merge them yourself without waiting for feedback from me. That makes it a tad easier for me to follow what is going on, while at the same time not slowing you down.

**Comment by felipenoris** [comment]
Alright!

**Pull request merged**
